# Generated by Django 5.1.1 on 2024-10-08 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ware',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost_method', models.CharField(choices=[('weighted_mean', 'Weighted Mean'), ('fifo', 'First In First Out (FIFO)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('input', 'Input (Restock)'), ('output', 'Output (Fulfillment)')], max_length=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ware')),
            ],
        ),
    ]
