# Generated by Django 5.1.1 on 2024-10-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='factor',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ware',
            name='cost_method',
            field=models.CharField(choices=[('weighted_mean', 'Weighted Mean'), ('fifo', 'FIFO')], max_length=50),
        ),
    ]
